# Generated by Django 3.0 on 2019-12-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_filepage_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepage',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
