# Generated by Django 3.0 on 2019-12-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20191216_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.FilePage'),
        ),
    ]
