# Generated by Django 3.0 on 2019-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='created_by',
            new_name='last_saved_by',
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
