# Generated by Django 3.0 on 2019-12-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20191216_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepage',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
