# Generated by Django 3.0 on 2019-12-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('hide', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('column_type', models.CharField(max_length=100, null=True)),
                ('max_value', models.CharField(help_text='Max value of Integers or Dates', max_length=128, null=True)),
                ('min_value', models.CharField(help_text='Min value of Integers of Dates', max_length=128, null=True)),
                ('column_allow_null', models.BooleanField(default=False)),
                ('column_allow_blank', models.BooleanField(default=False)),
                ('column_max_length', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('user_friendly_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('index_dimension', models.CharField(blank=True, max_length=256, null=True)),
                ('min_dimension_value', models.CharField(blank=True, max_length=256, null=True)),
                ('max_dimension_value', models.CharField(blank=True, max_length=256, null=True)),
                ('last_received', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('next_update', models.DateField(blank=True, null=True)),
                ('number_of_rows', models.IntegerField(blank=True, null=True)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('update_frequency', models.CharField(blank=True, choices=[('INTERMITTENT', 'Intermittent'), ('ANNUALLY', 'Annually'), ('BIANNUALLY', 'Bi-Annually'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily')], db_index=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=11)),
                ('short_name', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_file', models.ImageField(blank=True, null=True, upload_to='datasource_icons')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_street', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_city', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.DataSource')),
            ],
            options={
                'verbose_name_plural': 'sub agencies',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(null=True)),
                ('dataset', models.ManyToManyField(to='dictionary.DataSet')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(null=True)),
                ('datacolumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.DataColumn')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='sub_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SubAgency'),
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.DataSet'),
        ),
    ]
