# Generated by Django 3.0 on 2019-12-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacolumn',
            name='max_value',
            field=models.CharField(blank=True, help_text='Max value of Integers or Dates', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='datacolumn',
            name='min_value',
            field=models.CharField(blank=True, help_text='Min value of Integers of Dates', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='datacolumn',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
