# Generated by Django 3.0 on 2019-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20191217_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('subnav_order', models.IntegerField(blank=True, max_length=2, null=True, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
