# Generated by Django 3.0 on 2019-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='subnav_order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
