# Generated by Django 3.0 on 2019-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='content',
            field=models.TextField(blank=True, help_text='HTML CODE'),
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, help_text='HTML CODE'),
        ),
    ]
